version: 3
tasks:
  default:
    desc: Lists all the commands available
    silent: true
    cmds:
      - task --list-all
  prereq:
    desc: Does all the admin work for you to configure the repo
    silent: true
    cmds:
      - gh label list --json name | jq -r '.[].name' | while read -r label; do gh label delete "$label" --yes; done
      - gh label create "bump:major" --color "#B60205"
      - gh label create "bump:minor" --color "#FBCA04"
      - gh label create "bump:patch" --color "#0052CC"
      - pre-commit install
